[build]
  command = "echo 'No build step required'"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://ku-health-records-api.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/src/js/firebase-config.js"
  [headers.values]
  Cache-Control = "no-store, must-revalidate"

[[headers]]
  for = "/src/js/firebase-compat.js"
  [headers.values]
  Cache-Control = "no-store, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
  Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
  Content-Type = "text/css"
